-- MySQL Script generated by MySQL Workbench
-- Fri Jan 28 19:41:01 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema org
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema org
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `org` DEFAULT CHARACTER SET utf8 ;
USE `org` ;

-- -----------------------------------------------------
-- Table `org`.`organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `org`.`organization` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `org`.`relation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `org`.`relation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `organization_id` INT NOT NULL,
  `parent_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_relation_organization_idx` (`organization_id` ASC),
  INDEX `fk_relation_organization1_idx` (`parent_id` ASC),
  CONSTRAINT `fk_relation_organization`
    FOREIGN KEY (`organization_id`)
    REFERENCES `org`.`organization` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_relation_organization1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `org`.`organization` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
