version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./www:/var/www
      - ./logs:/var/log/nginx
    links:
      - php
    networks:
      - app

  php:
    build: ./images/php
    tty: true
    container_name: php
    working_dir: /var/www
    ports:
      - "9000:9000"
    volumes:
      - ./www:/var/www
    networks:
      - app

  mysql:
    build: ./images/mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - app
networks:
  app: